<?php
$_categories = $this->getCurrentChildCategories(); ?>
<ul class="categories-home-grid" data-equalizer data-equalize-on="medium">
    <?php $i = 0; ?>
    <?php foreach ($_categories as $_category): ?>
        <?php if ($_category->getIsActive()): ?>
            <?php $_category = Mage::getModel("catalog/category")->load($_category->getEntityId()); ?>
            <li class="item" data-equalizer-watch>
                <div class="category-image">
                    <?php if ($_category->getCategoryImage()) : ?>
                        <?php if ($additionalheadline = $_category->getAdditionalHeadline()): ?>
                            <?php $title = $this->helper('cms')->getBlockTemplateProcessor()->filter($this->helper('catalog/output')->categoryAttribute($_category, $_category->getAdditionalHeadline(), 'additional_headline')) ?>
                        <?php else: ?>
                            <?php $title = $this->htmlEscape($_category->getName()) ?>
                        <?php endif; ?>
                        <a href="<?php echo $_category->getURL() ?>"
                           title="<?php echo $this->htmlEscape($_category->getName()) ?>">
                            <img src="<?php echo $_category->getCategoryImage(125, 125) ?>"
                                 data-interchange="[<?php echo $_category->getCategoryImage(125, 125) ?>, small], [<?php echo $_category->getCategoryImage(150, 150) ?>, medium], [<?php echo $_category->getCategoryImage(250, 250) ?>, large]"
                                 alt="<?php echo $this->htmlEscape($_category->getName()) ?>"
                                 title="<?php echo $title ?>"/>
                        </a>
                    <?php endif; ?>
                    <h2 class="category-name">
                        <a href="<?php echo $_category->getURL() ?>"
                           title="<?php echo $this->htmlEscape($_category->getName()) ?>"><?php echo $this->htmlEscape($_category->getName()) ?></a>
                    </h2>
                </div>
            </li>
        <?php endif; ?>
        <?php $i++; ?>
    <?php endforeach; ?>
    <li class="item" data-equalizer-watch>
        <div class="category-image">
            <a href="<?php echo Mage::getUrl('') . 'hersteller/jura'; ?>"
               title="JURA Shop">
                <img src="<?php echo $this->getSkinUrl('dist/assets/img/jura-shop.jpg'); ?>" alt="JURA Shop"/>
            </a>
            <h2 class="category-name">
                <a href="<?php echo Mage::getUrl('') . 'hersteller/jura'; ?>"
                   title="JURA Shop">JURA Shop</a>
            </h2>
        </div>
    </li>
    <li class="item" data-equalizer-watch>
        <div class="category-image">
            <a href="<?php echo Mage::getUrl('') . 'hersteller/bartscher'; ?>"
               title="Bartscher Shop">
                <img src="<?php echo $this->getSkinUrl('dist/assets/img/bartscher-shop.png'); ?>" alt="Bartscher Shop"/>
            </a>
            <h2 class="category-name">
                <a href="<?php echo Mage::getUrl('') . 'hersteller/bartscher'; ?>"
                   title="Bartscher Shop">Bartscher Shop</a>
            </h2>
        </div>
    </li>
    <li class="item" data-equalizer-watch>
        <div class="category-image">
            <a href="<?php echo Mage::getUrl('') . 'hersteller/aliseo'; ?>"
               title="Aliseo Shop">
                <img src="<?php echo $this->getSkinUrl('dist/assets/img/aliseo-profishop.png'); ?>"
                     alt="Aliseo Shop"/>
            </a>
            <h2 class="category-name">
                <a href="<?php echo Mage::getUrl('') . 'hersteller/aliseo'; ?>"
                   title="Aliseo Shop">Aliseo Shop</a>
            </h2>
        </div>
    </li>
    <li class="item" data-equalizer-watch>
        <div class="category-image">
            <a href="<?php echo Mage::getUrl('') . 'hersteller/pacojet'; ?>"
               title="PacoJet Spezial">
                <img src="<?php echo $this->getSkinUrl('dist/assets/img/pacojet.jpg'); ?>"
                     alt="PacoJet Spezial"/>
            </a>
            <h2 class="category-name">
                <a href="<?php echo Mage::getUrl('') . 'hersteller/pacojet'; ?>"
                   title="PacoJet Spezial">PacoJet Spezial</a>
            </h2>
        </div>
    </li>
    <li class="item" data-equalizer-watch>
        <div class="category-image">
            <a href="<?php echo Mage::getUrl('') . 'hersteller/hugentobler'; ?>"
               title="Hugentobler Spezial">
                <img src="<?php echo $this->getSkinUrl('dist/assets/img/holdomat.jpg'); ?>"
                     alt="Hugentobler Spezial"/>
            </a>
            <h2 class="category-name">
                <a href="<?php echo Mage::getUrl('') . 'hersteller/hugentobler'; ?>"
                   title="Hugentobler Spezial">Hugentobler Spezial</a>
            </h2>
        </div>
    </li>
    <li class="item" data-equalizer-watch>
        <div class="category-image">
            <a href="<?php echo Mage::getUrl('') . 'altgeraeteentsorgung'; ?>"
               title="Umweltprämie & Abwrackprämie">
                <img src="<?php echo $this->getSkinUrl('dist/assets/img/abwrackpraemie-400x400.jpg'); ?>"
                     alt="Umweltprämie & Abwrackprämie"/>
            </a>
            <h2 class="category-name">
                <a href="<?php echo Mage::getUrl('') . 'altgeraeteentsorgung'; ?>"
                   title="Umweltprämie & Abwrackprämie">Umwelt-/ Abwrackprämie</a>
            </h2>
        </div>
    </li>
</ul>
<script type="text/javascript">
    jQuery('.categories-home-grid .item').on("click", function () {
        location.href = jQuery(this).find('a').attr('href');
    });
</script>