<?php
$_categories = $this->getCurrentChildCategories(); ?>
<ul class="categories-grid">
    <?php $i=0; ?>
    <?php foreach ($_categories as $_category): ?>
        <?php if ($_category->getIsActive()): ?>
            <?php $_category = Mage::getModel("catalog/category")->load($_category->getEntityId()); ?>
            <li>
                <div class="category-image">
                    <a href="<?php echo $_category->getURL() ?>"
                       title="<?php echo $this->htmlEscape($_category->getName()) ?>">
                        <?php if ($_imageUrl = $_category->getImageUrl()) : ?>
                            <img src="<?php echo $_imageUrl; ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>"/>
                        <?php endif; ?>
                    </a>
                    <div class="category-name">
                        <a href="<?php echo $_category->getURL() ?>"
                           title="<?php echo $this->htmlEscape($_category->getName()) ?>"><?php echo $this->htmlEscape($_category->getName()) ?></a>
                    </div>
                </div>
            </li>
        <?php endif; ?>
        <?php $i++; ?>
    <?php endforeach; ?>
</ul>