<?php
$_categories = $this->getCurrentChildCategories(); ?>
<ul class="categories-home-grid" data-equalizer data-equalize-on="medium">
    <?php $i=0; ?>
    <?php foreach ($_categories as $_category): ?>
        <?php if ($_category->getIsActive()): ?>
            <?php $_category = Mage::getModel("catalog/category")->load($_category->getEntityId()); ?>
            <li data-equalizer-watch>
                <div class="category-image">
                    <?php if ($_category->getCategoryImage()) : ?>
                    <a href="<?php echo $_category->getURL() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>">
                        <img data-interchange="[<?php echo $_category->getCategoryImage(125,125) ?>, small], [<?php echo $_category->getCategoryImage(180,180) ?>, medium], [<?php echo $_category->getCategoryImage(250,250) ?>, large]" alt="<?php echo $this->htmlEscape($_category->getName()) ?>"/>
                    </a>
                    <?php endif; ?>
                    <h2 class="category-name">
                        <a href="<?php echo $_category->getURL() ?>"
                           title="<?php echo $this->htmlEscape($_category->getName()) ?>"><?php echo $this->htmlEscape($_category->getName()) ?></a>
                    </h2>
                </div>
            </li>
        <?php endif; ?>
        <?php $i++; ?>
    <?php endforeach; ?>
    <li data-equalizer-watch>
        <div class="category-image">
            <a href="<?php echo Mage::getUrl('').'hersteller/bartscher'; ?>"
               title="Bartscher Shop">
                <img src="<?php echo $this->getSkinUrl('dist/assets/img/bartscher-shop.png'); ?>" alt="Bartscher Shop"/>
            </a>
            <h2 class="category-name">
                <a href="<?php echo Mage::getUrl('').'hersteller/bartscher'; ?>"
                   title="Bartscher Shop">Bartscher Shop</a>
            </h2>
        </div>
    </li>
    <li data-equalizer-watch>
        <div class="category-image">
            <a href="<?php echo Mage::getUrl('').'hersteller/aliseo'; ?>"
               title="Aliseo Profishop">
                <img src="<?php echo $this->getSkinUrl('dist/assets/img/aliseo-profishop.png'); ?>" alt="Aliseo Profishop"/>
            </a>
            <h2 class="category-name">
                <a href="<?php echo Mage::getUrl('').'hersteller/aliseo'; ?>"
                   title="Aliseo Profishop">Aliseo Profishop</a>
            </h2>
        </div>
    </li>
    <li data-equalizer-watch>
        <div class="category-image">
            <a href="<?php echo Mage::getUrl('').'altgeraeteentsorgung'; ?>"
               title="Umweltprämie & Abwrackprämie">
                <img src="<?php echo $this->getSkinUrl('dist/assets/img/umwelt_abwrackpraemie.jpg'); ?>" alt="Umweltprämie & Abwrackprämie"/>
            </a>
            <h2 class="category-name">
                <a href="<?php echo Mage::getUrl('').'altgeraeteentsorgung'; ?>"
                   title="Umweltprämie & Abwrackprämie">Umwelt-/ Abwrackprämie</a>
            </h2>
        </div>
    </li>
</ul>