<?php
/**
 * @category    Mana
 * @package     ManaPro_FilterGroup
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Mage_Core_Block_Template */
?>
<?php if (Mage::getStoreConfig('mana_filters/advanced/collapseable_groups')) : ?>
    <div class="m-filter-group-expand-collapse">
        <div class="btn-expand-collapse"></div>
    </div>
<?php endif; ?>
