<footer>
    <div class="footer-top">
        <a href="#top" id="backtotop">
            <div class="backtotop">
                <span class="navFooterBackToTopText"><?php echo $this->__('Zur&uuml;ck zum Seitenanfang') ?></span>
            </div>
        </a>
    </div>
    <div class="footer-extras">
        <div class="content">
            <a href="<?php echo Mage::getUrl('', array('_direct' => 'lieferung')); ?>">
                <img class="lazy"
                     src="<?php echo $this->getSkinUrl('dist/assets/img/versandkostenfrei.png') ?>"
                     alt="kostenfreie Lieferung ab 99 EUR"
                     title="kostenfreie Lieferung ab 99 EUR"
                     width="174"
                     height="50"
                />
            </a>
            <a href="<?php echo Mage::getUrl('', array('_direct' => 'topshop')); ?>">
                <img class="lazy"
                     src="<?php echo $this->getSkinUrl('dist/assets/img/CoBi_TopShopProfessional2023_Logo_Hor_Gastronomiebedarf.png'); ?>"
                     alt="ComputerBild TopShop 2023 Gastronomiebedarf"
                     title="ComputerBild TopShop 2023 Gastronomiebedarf"
                     width="200"
                />
            </a>
            <img class="footer-logo lazy"
                 src="<?php echo $this->getSkinUrl('dist/assets/img/gastrodax-logo.png'); ?>"
                 alt="Gastrodax"
                 title="Gastrodax"
                 width="240"
                 height="46"
            />
            <a href="https://www.newgastroline.de" target="_blank">
                <img class="lazy"
                     src="<?php echo $this->getSkinUrl('dist/assets/img/30jahre.png') ?>"
                     alt="30 Jahre New Gastroline GmbH"
                     title="30 Jahre New Gastroline GmbH"
                     width="80"
                     height="34"
                />
            </a>
        </div>
    </div>
    <div class="footer-info">
        <div class="content">
            <div class="footer_links">
                <p><?php echo $this->__('Informationen') ?></p>
                <ul>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'themen')); ?>"><?php echo $this->__('Themen') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'lieferung')); ?>"><?php echo $this->__('Versandkosten') ?></a>
                    </li>
                    <li>
                        <a class="quality"><?php echo $this->__('Sicher einkaufen') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'zertifizierter-haendler')); ?>"><?php echo $this->__('Zertifikate') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'bestellvorgang')); ?>"><?php echo $this->__('Bestellvorgang') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'leasing-mietkauf')); ?>"><?php echo $this->__('Finanzierung %') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'zahlungsarten')); ?>"><?php echo $this->__('Zahlungsarten') ?></a>
                    </li>
                    <?php if (Mage::app()->getStore()->getId() == '5'): /* B2C */ ?>
                        <li>
                            <a href="<?php echo Mage::getUrl('', array('_direct' => 'widerrufsbelehrung')); ?>"><?php echo $this->__('Widerrufsbelehrung') ?></a>
                        </li>
                        <li>
                            <a href="<?php echo Mage::getUrl('', array('_direct' => 'widerrufsformular')); ?>"><?php echo $this->__('Widerrufsformular') ?></a>
                        </li>
                    <?php endif ?>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'batteriegesetz')); ?>"><?php echo $this->__('Batteriegesetz') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'referenzen')); ?>"><?php echo $this->__('Referenzen') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl(''); ?>"><?php echo $this->__('Startseite') ?></a>
                    </li>
                </ul>
                <div class="reveal large" id="quality" data-reveal></div>
                <script>
                    jQuery('.quality').click(function () {
                        jQuery.ajax({
                            url: '<?php echo $this->getUrl('ajax/cms/block/id/14');?>',
                            beforeSend: function () {
                                jQuery('#reveal-wait').show();
                            }
                        })
                            .done(function (data) {
                                jQuery('#reveal-wait').hide();
                                jQuery('#quality').html(data).foundation('open');
                            });
                    });
                </script>
            </div>
            <div class="footer_service">
                <p><?php echo $this->__('Kundenservice') ?></p>
                <ul>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'contacts')); ?>"><?php echo $this->__('Kontakt') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'grosskuechenplanung')); ?>"><?php echo $this->__('Gro&szlig;k&uuml;chenplanung') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'leistungen')); ?>"><?php echo $this->__('Leistungen') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'altgeraeteentsorgung')); ?>"><?php echo $this->__('Altger&auml;teentsorgung') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'montage')); ?>"><?php echo $this->__('Montage-Service') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'service')); ?>"><?php echo $this->__('Gastro-Service') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'leasing-mietkauf')); ?>"><?php echo $this->__('Leasing/Mietkauf') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'streitschlichtung')); ?>"><?php echo $this->__('Streitschlichtung') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/fax/faxbestellung.pdf'; ?>"
                           target="_blank">Faxbestellung</a></li>
                    <?php echo $this->getChildHtml('store_switcher', false) ?>
                </ul>
            </div>
            <div class="footer_manufactures">
                <p><?php echo $this->__('Unsere starken Gastro-Marken') ?></p>
                <ul>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/bartscher')); ?>"><?php echo $this->__('Bartscher') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/brita-professional')); ?>"><?php echo $this->__('BRITA Professional') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/jura')); ?>"><?php echo $this->__('JURA') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/panasonic')); ?>"><?php echo $this->__('Panasonic') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/rational')); ?>"><?php echo $this->__('RATIONAL') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/winterhalter')); ?>"><?php echo $this->__('WINTERHALTER') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/vaihinger-sanomat')); ?>"><?php echo $this->__('Sanomat') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/mkn')); ?>"><?php echo $this->__('MKN') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/liebherr')); ?>"><?php echo $this->__('Liebherr') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller')); ?>"><?php echo $this->__('weitere Gastro-Marken') ?></a>
                    </li>
                </ul>
            </div>
            <div class="footer_categories">
                <p><?php echo $this->__('Beliebte Gastro-Artikel') ?></p>
                <ul>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/rational/kombidaempfer')); ?>"><?php echo $this->__('Rational Kombid&auml;mpfer') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/winterhalter')); ?>"><?php echo $this->__('Winterhalter Sp&uuml;lmaschinen') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/jura/kaffeevollautomaten')); ?>"><?php echo $this->__('JURA Kaffeevollautomaten') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/seltmann-weiden/salzburg')); ?>"><?php echo $this->__('Seltmann Weiden Salzburg') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/bartscher/salamander')); ?>"><?php echo $this->__('Bartscher Salamander') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/mkn/kombidaempfer')); ?>"><?php echo $this->__('MKN Kombid&auml;mpfer') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/rational/ivario-pro')); ?>"><?php echo $this->__('Rational iVario Pro') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/picard-und-wielputz')); ?>"><?php echo $this->__('Picard &amp; Wielp&uuml;tz Besteck') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/panasonic')); ?>"><?php echo $this->__('Panasonic Mikrowellen') ?></a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'hersteller/aliseo/kosmetikspiegel')); ?>"><?php echo $this->__('Aliseo Kosmetikspiegel') ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-payments">
        <div class="payments">
            <ul>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'zahlungsarten#paypal')); ?>">
                        <img class="lazy" src="<?php echo $this->getSkinUrl('dist/assets/img/paypal-white.png') ?>"
                             alt="PayPal Logo" title="PayPal Logo" width="100" height="75"/> </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'zahlungsarten#klarna')); ?>">
                        <img class="lazy" src="<?php echo $this->getSkinUrl('dist/assets/img/klarna-white.png') ?>"
                             alt="Klarna Logo" title="Klarna Logo" width="100" height="75"/> </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'zahlungsarten#sofort')); ?>">
                        <img class="lazy" src="<?php echo $this->getSkinUrl('dist/assets/img/sofort-white.png') ?>"
                             alt="Sofortüberweisung Logo" title="Sofortüberweisung Logo" width="100" height="75"/> </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'zahlungsarten#moneyorder')); ?>">
                        <img class="lazy" src="<?php echo $this->getSkinUrl('dist/assets/img/vorkasse-white.png') ?>"
                             alt="Vorkasse Logo" title="Vorkasse Logo" width="100" height="75"/> </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'zahlungsarten#creditcard')); ?>">
                        <img class="lazy" src="<?php echo $this->getSkinUrl('dist/assets/img/creditcard-white.png') ?>"
                             alt="Kreditkarte Logo" title="Kreditkarte Logo" width="100" height="75"/> </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'zahlungsarten#invoice')); ?>">
                        <img class="lazy" src="<?php echo $this->getSkinUrl('dist/assets/img/invoice-white.png') ?>"
                             alt="Rechnung Logo" title="Rechnung Logo" width="100" height="75"/> </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'zahlungsarten#finanz')); ?>">
                        <img class="lazy" src="<?php echo $this->getSkinUrl('dist/assets/img/finanz-white.png') ?>"
                             alt="Finanzierung Logo" title="Finanzierung Logo" width="100" height="75"/> </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'zahlungsarten#sepa')); ?>">
                        <img class="lazy" src="<?php echo $this->getSkinUrl('dist/assets/img/sepa-white.png') ?>"
                             alt="Sepa Lastschrift Logo" title="Sepa Lastschrift Logo" width="100" height="75"/> </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="org">
            <ul>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'agb')); ?>"><?php echo $this->__('AGB') ?></a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'impressum')); ?>"><?php echo $this->__('Impressum') ?></a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'datenschutz')); ?>"><?php echo $this->__('Datenschutz') ?></a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('', array('_direct' => 'sitemap')); ?>"><?php echo $this->__('Sitemap') ?></a>
                </li>
                <li>
                    <a class="hints"><?php echo $this->__('Hinweise') ?></a>
                </li>
            </ul>
            <div class="reveal large" id="hints" data-reveal></div>
            <script>
                jQuery('.hints').click(function () {
                    jQuery.ajax({
                        url: '<?php echo $this->getUrl('ajax/cms/block/id/60');?>',
                        beforeSend: function () {
                            jQuery('#reveal-wait').show();
                        }
                    })
                        .done(function (data) {
                            jQuery('#reveal-wait').hide();
                            jQuery('#hints').html(data).foundation('open');
                        });
                });
            </script>
        </div>
        <div class="social">
            <ul>
                <li>
                    <a href="https://facebook.com/gastrodax/" target="_blank" rel="nofollow noopener noreferrer" title="<?php echo $this->__('Facebook') ?>"><i
                            class="fab fa-facebook-square"></i></a></li>
                <li><a href="https://www.youtube.com/channel/UCTr6z7_W4adeggGR1Sa717g" target="_blank"
                       rel="nofollow noopener noreferrer" title="<?php echo $this->__('YouTube') ?>"><i class="fab fa-youtube-square"></i></a>
                </li>
                <li>
                    <a href="https://twitter.com/gastrodax" target="_blank" rel="nofollow noopener noreferrer" title="<?php echo $this->__('Twitter') ?>"><i
                            class="fab fa-twitter-square"></i></a></li>
            </ul>
        </div>
        <div class="copyright">
            <p>© 1990 - <?php echo date("Y"); ?> New Gastroline GmbH</p>
        </div>
    </div>
</footer>
<div id="GdTrustbadge"></div>
<?php
/**
 * This is an example of integrating Trusted Shops Customer Reviews
 * marked with structured data into your website
 * Make sure you replace value of $tsid with your Trusted Shops ID
 * Make sure you have a writing permission to the
 * folder set in $cacheFileName
 * Requires version PHP 5.+
 */
$tsId = 'X6B5E9287FD5871CE74DA1B1775EB2D64';
$cacheFileName = Mage::getBaseDir('base') . '/var/tmp/' . $tsId . '.json';
$cacheTimeOut = 43200; // half a day
$apiUrl = 'https://api.trustedshops.com/rest/public/v2/shops/' . $tsId . '/quality/reviews.json';
$reviewsFound = false;

if (!function_exists('trustedshopscachecheck')) {
    function trustedshopscachecheck($filename_cache, $timeout = 10800)
    {
        if (file_exists($filename_cache) && time() - filemtime($filename_cache) < $timeout) {
            return true;
        }
        return false;
    }
}

// check if cached version exists
if (!trustedshopscachecheck($cacheFileName, $cacheTimeOut)) {
    // load fresh from API
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, false);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
    curl_setopt($ch, CURLOPT_URL, $apiUrl);
    $output = curl_exec($ch);
    if ($output) {
        file_put_contents($cacheFileName, $output);
    }
    curl_close($ch);
    // Write the contents back to the file
    // Make sure you can write to file's destination

}
if ($jsonObject = json_decode(file_get_contents($cacheFileName), true)) {
    $result = $jsonObject['response']['data']['shop']['qualityIndicators']['reviewIndicator']['overallMark'];
    $count = $jsonObject['response']['data'] ['shop']['qualityIndicators']['reviewIndicator']['activeReviewCount'];
    $shopName = $jsonObject['response']['data']['shop']['name'];
    $max = "5.00";
    if ($count > 0) {
        $reviewsFound = true;
    }
}
if ($reviewsFound) {
    // Output aggregated reviews markup:
    $ts_snippet = '<script type="application/ld+json">';
    $ts_snippet .= '{';
    $ts_snippet .= '"@context": "http://schema.org",';
    $ts_snippet .= '"@type": "Organization",';
    $ts_snippet .= '"name": "' . $shopName . '",';
    $ts_snippet .= '"url": "' . Mage::getBaseUrl() . '",';
    $ts_snippet .= '"logo": "' . $this->getSkinUrl('dist/assets/img/logo.png') . '",';
    $ts_snippet .= '"contactPoint": [{';
    $ts_snippet .= '"@type": "ContactPoint",';
    $ts_snippet .= '"telephone": "+49-8004566000",';
    $ts_snippet .= '"contactType": "customer service"';
    $ts_snippet .= '}],';
    $ts_snippet .= '"sameAs": [';
    $ts_snippet .= '"https://www.facebook.com/gastrodax",';
    $ts_snippet .= '"https://twitter.com/gastrodax",';
    $ts_snippet .= '"https://www.youtube.com/channel/UCTr6z7_W4adeggGR1Sa717g"';
    $ts_snippet .= '],';
    $ts_snippet .= '"aggregateRating" : {';
    $ts_snippet .= '"@type": "AggregateRating",';
    $ts_snippet .= '"ratingValue" : "' . $result . '",';
    $ts_snippet .= '"bestRating" : "' . $max . '",';
    $ts_snippet .= '"ratingCount" : "' . $count . '"';
    $ts_snippet .= '}}';
    $ts_snippet .= '</script>';
    echo $ts_snippet;
}