<?php if ($this->displayNoscriptNotice()): ?>
    <noscript>
        <div class="callout nojs alert global-site-notice noscript">
            <p><?php echo $this->__('Bitte aktivieren Sie Javascript in Ihren Browser.'); ?></p>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($this->displayDemoNotice()): ?>
    <div class="global-site-notice demo-notice">
        <div class="notice-inner">
            <p><?php echo $this->__('This is a demo store. Any orders placed through this store will not be honored or fulfilled.') ?></p>
        </div>
    </div>
<?php endif; ?>
