<div class="reveal large" id="tuvsud" data-reveal></div>
<script>
    jQuery('.tuvsudmodal').click(function () {
        jQuery.ajax({
            url: '<?php echo $this->getUrl('ajax/cms/block/id/27');?>',
            beforeSend: function () {
                jQuery('#reveal-wait').show();
            }
        })
            .done(function (data) {
                jQuery('#reveal-wait').hide();
                jQuery('#tuvsud').html(data).foundation('open');
            });
    });
</script>