<div class="reveal large" id="tuvsud" data-reveal></div>
<div id="reveal-wait" class="please-wait" style="display:none;">
    <div class="centered">
        <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw margin-bottom"></i>
    </div>
</div>
<script>
    jQuery('.tuvsudmodal').click(function () {
        jQuery.ajax({
            url: '<?php echo $this->getUrl('ajax/cms/block/id/27');?>',
            beforeSend: function () {
                jQuery('#reveal-wait').show();
            }
        })
            .done(function (data) {
                jQuery('#reveal-wait').hide();
                jQuery('#tuvsud').html(data).foundation('open');
            });
    });
</script>