<?php
/**
 * @project gastrodax
 *
 * @author pbreitsprecher
 * @copyright 2016
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 *
 * @last_modified 22.09.16 14:27
 * @file trustedshops.phtml
 *
 */

$tsId = 'X6B5E9287FD5871CE74DA1B1775EB2D64';
$cacheFileNameReviewsApi = Mage::getBaseDir('tmp') . '/' . $tsId . '_reviews.json';
$cacheFileNameQiApi = Mage::getBaseDir('tmp') . '/' . $tsId . '_quality.json';
$cacheTimeOut = 43200; // half a day
$reviewsApiUrl = 'http://api.trustedshops.com/rest/public/v2/shops/' . $tsId . '/reviews.json';
$qiApiUrl = 'http://api.trustedshops.com/rest/public/v2/shops/' . $tsId . '/quality.json';
$xmlFound = false;
if (!function_exists('cachecheck')) {
    function cachecheck($filename_cache, $timeout = 10800)
    {
        if (file_exists($filename_cache) && time() - filemtime($filename_cache) < $timeout) {
            return true;
        }
        return false;
    }
}
// check if cached version exists
if (!cachecheck($cacheFileNameReviewsApi, $cacheTimeOut)) {
    // load fresh from API
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, false);
    curl_setopt($ch, CURLOPT_URL, $reviewsApiUrl);
    $output = curl_exec($ch);
    curl_close($ch);
    // Write the contents back to the file
    // Make sure you can write to file's destination
    file_put_contents($cacheFileNameReviewsApi, $output);
}
if (!cachecheck($cacheFileNameQiApi, $cacheTimeOut)) {
    // load fresh from API
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, false);
    curl_setopt($ch, CURLOPT_URL, $qiApiUrl);
    $output = curl_exec($ch);
    curl_close($ch);
    // Write the contents back to the file
    // Make sure you can write to file's destination
    file_put_contents($cacheFileNameQiApi, $output);
}
$jsonObjectReviews = json_decode(file_get_contents($cacheFileNameReviewsApi), true);
$jsonObjectQi = json_decode(file_get_contents($cacheFileNameQiApi), true);
if ($jsonObjectReviews && $jsonObjectQi) {
    $result = $jsonObjectQi['response']['data']['shop']['qualityIndicators']['reviewIndicator']['overallMark'];
    $count = $jsonObjectQi['response']['data']['shop']['qualityIndicators']['reviewIndicator']['activeReviewCount'];
    $shopName = $jsonObjectReviews['response']['data']['shop']['name'];
    $reviewsList = $jsonObjectReviews['response']['data']['shop']['reviews'];
    $max = "5.00";
    if ($count > 0) { ?>
        <div class="global">
            <div class="head">
                <div class="logo"><img src="<?php echo $this->getSkinUrl('images/trusted-shops.png'); ?>"
                                       alt="TrustedShops Logo"/></div>
                <div class="title"><?php echo $this->__('Trusted Shops') ?>
                    <span><?php echo $this->__('Kundenbewertungen') ?></span></div>
            </div>
            <div class="stars"></div>
            <div class="review">
                <div itemscope itemtype="http://schema.org/LocalBusiness">
                <span itemprop="aggregateRating"
                      itemscope
                      itemtype="http://schema.org/AggregateRating">
                <span itemprop="ratingValue"
                      class="ratingNote">
                    <?php echo $result; ?>
                </span> /
                <span itemprop="bestRating">
                    <?php echo $max; ?>
                </span> <br>von
                <span itemprop="ratingCount">
                    <?php echo $count; ?>
                </span>
                     Bewertungen
                </span>
                </div>
                <a class="ts-button"
                   href="https://www.trustedshops.eu/buyerrating/info_<?php echo $tsId; ?>.html"
                   target="_blank">
                    Zu den Bewertungen
                </a>
            </div>
            <script>
                jQuery('.stars').raty({
                    readOnly: true,
                    numberMax: <?php echo $max; ?>,
                    score: <?php echo $result; ?>,
                    half: true
                });
            </script>
        </div>
        <div class="separat">
            <div class="users">
                <h6><?php echo $this->__('Kundenmeinungen:') ?></h6>
                <ul class="reviews-slider owl-carousel owl-theme">
                    <?php
                    /* Set Locale for Date output */
                    setlocale(LC_ALL, 'de_DE.utf8');
                    $index = 0;
                    foreach ($reviewsList as $review) {
                        $reviewDateRichSnippets = date('Y-m-d', strtotime($review['changeDate']));
                        $reviewDateFormatted = strftime('%d. %B %Y', strtotime($review['changeDate']));
                        $reviewComment = $review['comment'];
                        $reviewRating = $review['mark'];
                        $reviewRatingString = $review['markDescription'];
                        if (isset($review['statements'])) {
                            $shopReply = $review['statements'][0]['comment'];
                        }
                        ?>
                        <li>
                            <div class="user-reviews">
                                <span class="user-star-<?php echo $index; ?>"></span>
                                <p><?php echo $reviewComment; ?></p>
                                <span class="user-date">vom <?php echo $reviewDateFormatted; ?></span>
                                <script>
                                    jQuery('.user-star-<?php echo $index; ?>').raty({
                                        readOnly: true,
                                        numberMax: <?php echo $max; ?>,
                                        score: <?php echo $reviewRating; ?>,
                                        half: true
                                    });
                                </script>
                            </div>
                        </li>
                        <?php
                        $index++;
                    } ?>
                </ul>
            </div>
        </div>
    <?php }
}
?>