<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
* @package Banners Lite (System)
*/
?>
<?php
if (Mage::helper('ambannerslite')->isEnable()):
    if ($this->getImage() && $this->getEnabled()) {
        ?><img class="ampromo-label" alt="<?php echo $this->getAlt(); ?>" src="<?php echo $this->getImage(); ?>">
    <?php } ?>
    <div style="clear: both;"></div>
<?php endif; ?>