<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image">
                            <?php $_imgSize = 300; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        </a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                            title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                                </h2>
                                <?php if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <?php endif; ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if ($_product->isSaleable()): ?>
                                    <p>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                class="button btn-cart"
                                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    </p>
                                <?php else: ?>
                                    <p class="availability out-of-stock">
                                        <span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped ?>"
                                       class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
        <?php else: ?>
        <?php // Grid Mode ?>
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
            <ul class="products-grid">
                <?php
                $i = 0;
                $min = 1;
                $max = 6;
                $random = rand($min, $max);
                ?>
                <?php foreach ($_productCollection as $_product): ?>
                <?php if ($i == $random) { ?>
                    <li class="item action">
                        <a href="<?php echo Mage::getUrl('', array('_direct' => 'kaffee')); ?>" title="Kaffee und Kaffeebohnen">
                            <img src="<?php echo $this->getSkinUrl('dist/assets/img/piazza-doro-banner.jpg') ?>"
                                 alt="Piazza Doro"/>
                        </a>
                        <div class="product-name">
                            <a href="<?php echo Mage::getUrl('', array('_direct' => 'kaffee')); ?>" title="Kaffee &amp; Kaffeebohnen">Kaffee &amp; Kaffeebohnen</a>
                        </div>
                    </li>
                <?php } ?>
                <li class="item">
                    <?php if ($_product->getFinalPrice() < $_product->getPrice()) { ?>
                        <?php $_savingPercent = 100 - round(($_product->getFinalPrice() / $_product->getPrice()) * 100); ?>
                        <div class="special-ribbon"><span><?php echo $_savingPercent; ?>% Rabatt</span>
                        </div>
                    <?php } ?>
                    <div class="products-image float-center">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image small-centered">
                            <img
                                    src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>"
                                    width="200" height="200"
                                    alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        </a>
                    </div>
                    <div class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                 title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    </div>
                    <?php if ($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                    <?php echo $this->getLayout()->createBlock('catalog/product_price')
                        ->setTemplate('catalog/product/price_catalog.phtml')
                        ->setProduct($_product)
                        ->setDisplayMinimalPrice(true)
                        ->setIdSuffix($idSuffix = 'amit')
                        ->toHtml(); ?>
                    <?php //echo $this->getPriceHtml($_product, true) ?>
                    <?php if ($_product->getData('commissioning') == 1): ?>
                        <?php $productAttribute = $_product->getResource()->getAttribute('commissioning'); ?>
                        <?php $_label = $productAttribute->getStoreLabel(Mage::app()->getStore()->getId()); ?>
                        <span class="commissioning"><?php echo $_label; ?></span>
                    <?php endif; ?>
                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                        <div class="compare">
                            <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
                        </div>
                    <?php endif; ?>
                    <?php endforeach ?>
            </ul>
            <script type="text/javascript">
                jQuery('.item').on("click", function () {
                    location.href = jQuery(this).find('a').attr('href');
                });
            </script>
        <?php endif; ?>
        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
