<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
function clean($string)
{

    $string = str_replace(' ', '-', $string); // Replaces all spaces with hyphens.
//$string = preg_replace('/[^A-Za-z0-9\-]/', '', $string); // Removes special chars.
    $string = strtolower($string);
    $utf8 = array(
        '/[áàâãªä]/u' => 'a',
        '/[ÁÀÂÃÄ]/u' => 'A',
        '/[ÍÌÎÏ]/u' => 'I',
        '/[íìîï]/u' => 'i',
        '/[éèêë]/u' => 'e',
        '/[ÉÈÊË]/u' => 'E',
        '/[óòôõºö]/u' => 'o',
        '/[ÓÒÔÕÖ]/u' => 'O',
        '/[úùûü]/u' => 'u',
        '/[ÚÙÛÜ]/u' => 'U',
        '/ç/' => 'c',
        '/Ç/' => 'C',
        '/ñ/' => 'n',
        '/Ñ/' => 'N',
        '/–/' => '-', // UTF-8 hyphen to "normal" hyphen
        '/[’‘‹›‚]/u' => ' ', // Literally a single quote
        '/[“”«»„]/u' => ' ', // Double quote
        '/ /' => ' ', // nonbreaking space (equiv. to 0x160)
    );

    return preg_replace(array_keys($utf8), array_values($utf8), $string); // Replaces multiple hyphens with single one.
}

$_productCollection = Mage::getModel('catalog/product')->getCollection();
$_productCollection->addAttributeToSelect('*')
    ->addFieldToFilter('visibility', array(
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
    ))//showing just products visible in catalog or both search and catalog
    ->addFinalPrice()
//                        ->addAttributeToSort('price', 'asc') //in case we would like to sort products by price
    //->addAttributeToFilter('top_product', array('eq' => 1))
    ->addAttributeToFilter(array(array('attribute' => 'top_product', 'eq' => 1)))
    ->getSelect()
    ->limit(11)//we can specify how many products we want to show on this page
    ->order(new Zend_Db_Expr('RAND()')) //in case we would like to sort products randomly
;

Mage::getModel('review/review')->appendSummary($_productCollection);

$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="top-products category-products">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i = 0; ?>
        <div class="top-products-slider products-grid owl-carousel owl-theme row small-up-1 medium-up-4 large-up-6">
            <?php $i = 0;
            foreach ($_productCollection as $_product): ?>
                <div class="item">
                    <div class="content">
                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                    title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                        </h3>
                        <div class="products-image float-center">
                            <?php if ($_product->getFinalPrice() < $_product->getPrice()) { ?>
                                <?php $_savingPercent = 100 - round(($_product->getFinalPrice() / $_product->getPrice()) * 100); ?>
                                <div class="special-ribbon"><span><?php echo $_savingPercent; ?>% Rabatt</span>
                                </div>
                            <?php } ?>
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                               class="product-image small-centered">
                                <img
                                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>"
                                        width="200" height="200"
                                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            </a>
                        </div>
                        <?php if ($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                        <div class="extra">

                            <?php if ($_product->getAttributeText('manufacturer')): ?>
                                <?php $brand = $_product->getAttributeText('manufacturer') ?>
                                <div class="product-brand">
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>catalog/brands/<?php echo clean($brand) ?>.png"
                                         alt="<?php echo $brand ?> Logo">
                                </div>
                            <?php endif; ?>

                            <?php echo $this->getLayout()->createBlock('catalog/product_price')
                                ->setTemplate('catalog/product/price_catalog.phtml')
                                ->setProduct($_product)
                                ->setDisplayMinimalPrice(true)
                                ->setIdSuffix($idSuffix = 'amit')
                                ->toHtml(); ?>
                            <?php //echo $this->getPriceHtml($_product, true) ?>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
<?php endif; ?>
