<?php
if (!function_exists('clean')) {
    function clean($string)
    {

        $string = str_replace(' ', '-', $string); // Replaces all spaces with hyphens.
//$string = preg_replace('/[^A-Za-z0-9\-]/', '', $string); // Removes special chars.
        $string = strtolower($string);
        $utf8 = array(
            '/[áàâãª]/u' => 'a',
            '/[ÁÀÂÃ]/u' => 'A',
            '/[äÄ]/u' => 'ae',
            '/[ÍÌÎÏ]/u' => 'I',
            '/[íìîï]/u' => 'i',
            '/[éèêë]/u' => 'e',
            '/[ÉÈÊË]/u' => 'E',
            '/[óòôõºö]/u' => 'o',
            '/[ÓÒÔÕÖ]/u' => 'O',
            '/[úùûü]/u' => 'u',
            '/[ÚÙÛÜ]/u' => 'U',
            '/ç/' => 'c',
            '/Ç/' => 'C',
            '/ñ/' => 'n',
            '/Ñ/' => 'N',
            '/–/' => '-', // UTF-8 hyphen to "normal" hyphen
            '/[’‘‹›‚]/u' => ' ', // Literally a single quote
            '/[“”«»„]/u' => ' ', // Double quote
            '/ /' => ' ', // nonbreaking space (equiv. to 0x160)
        );

        return preg_replace(array_keys($utf8), array_values($utf8), $string); // Replaces multiple hyphens with single one.
    }
}
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<?php echo $this->getChildHtml('revslider-header') ?>
    <div class="product-view-revslider">
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post"
                  id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <?php echo $this->getBlockHtml('formkey') ?>
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
                    <input type="hidden" name="related_product" id="related-products-field" value=""/>
                </div>
                <div class="product-img-box">
                    <?php echo $this->getChildHtml('media') ?>
                </div>
                <div class="product-shop">
                    <ul class="pricing-table">
                        <li class="title">
                            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                        </li>
                        <li class="bullet-item">
                            <p class="sku"><?php echo $this->__('Artikelnummer: ') ?>
                                <span><?php echo $_product->getSku() ?></span>
                            </p>
                        </li>
                        <?php echo $this->getChildHtml('product_type_data') ?>
                        <?php if (!empty($_product->getAttributeText('manufacturer'))): ?>
                            <li class="description">
                                <div class="product-brand">
                                    <?php $brand = $_product->getAttributeText('manufacturer') ?>
                                    <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'hersteller/' . clean($brand) ?>">
                                        <img class="lazy" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>catalog/brands/<?php echo clean($brand) ?>.png"
                                             alt="<?php echo $brand ?> Logo"
                                             title="<?php echo $this->__('Zeige alle Artikel von %s', $brand) ?>">
                                    </a>
                                </div>
                            </li>
                            <li class="bullet-item">
                                <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'hersteller/' . clean($brand) ?>">
                                    <?php echo $this->__('Zeige alle Artikel von %s', $brand) ?>
                                </a>
                            </li>
                        <?php endif; ?>
                        <?php if (!$this->hasOptions()): ?>
                            <?php if ($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                                <?php if ($this->helper('wishlist')->isAllow() || $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php echo $this->getChildHtml('addto') ?>
                            <?php echo $this->getChildHtml('extra_buttons') ?>
                        <?php elseif (!$_product->isSaleable()): ?>
                            <li class="cta-button">
                                <?php echo $this->getChildHtml('addto') ?>
                            </li>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('alert_urls') ?>
                        <?php echo $this->getChildHtml('extrahint') ?>
                        <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                            <li class="bullet-item">
                                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                            </li>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('other'); ?>
                    </ul>
                </div>
            </form>
    </div>
<?php echo $this->getChildHtml('revslider-block-1') ?>
<?php echo $this->getChildHtml('revslider-block-2') ?>
<?php echo $this->getChildHtml('revslider-block-3') ?>
<?php echo $this->getChildHtml('revslider-block-4') ?>
<?php echo $this->getChildHtml('revslider-block-5') ?>
<?php echo $this->getChildHtml('revslider-block-6') ?>
