<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <?php echo $this->getChildHtml('global_messages') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="off-canvas-wrapper">
            <div class="off-canvas-absolute position-left" id="offCanvas" data-off-canvas>
                <?php echo $this->getLayout()->createBlock('page/html_topmenu')->setTemplate('page/html/topmenu.phtml')->toHtml(); ?>
            </div>
            <div class="off-canvas-content" data-off-canvas-content>
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="main-container col3-layout">
                    <div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
                    <div id="main" class="col-main">
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                    <div class="col-right sidebar"><?php echo $this->getChildHtml('right') ?></div>
                </div>
                <?php echo $this->getChildHtml('footer') ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>