<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <?php echo $this->getChildHtml('global_messages') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="off-canvas-wrapper">
            <div class="off-canvas-absolute position-left" id="offCanvas" data-off-canvas data-transition="overlap">
                <?php echo $this->getLayout()->createBlock('page/html_topmenu')->setTemplate('page/html/topmenu.phtml')->toHtml(); ?>
            </div>
            <div class="off-canvas-content" data-off-canvas-content>
                <div class="headbanner">
                    <div class="banner">
                        <img src="<?php echo $this->getSkinUrl('dist/assets/img/flaschenpost.jpg'); ?>" alt="Contact Banner" />
                    </div>
                </div>
                <div class="main-container col1-layout">
                    <div class="col-main">
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
                <?php echo $this->getChildHtml('footer') ?>
            </div>
            <div class="off-canvas position-right" id="offCanvasRightCart" data-off-canvas data-transition="overlap">
                <?php echo $this->getChildHtml('cart_sidebar') ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>