<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <script type="text/javascript">
        //<![CDATA[
        function captcha() {
            var v = grecaptcha.getResponse();
            if (v.length == 0) {
                document.getElementById('recaptcha_validation').value = "";
                return false;
            }
            if (v.length != 0) {
                document.getElementById('recaptcha_validation').value = "1";
                return true;
            }
        };
        //]]>
    </script>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" data-abide novalidate
          onsubmit="return jQuery(this) && captcha()">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="registered-users">
            <div class="content">
                <h2><?php echo $this->__('Registered Customers') ?></h2>
                <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                <div class="email-field">
                    <label for="email"><?php echo $this->__('Email Address') ?>
                        <small><?php echo $this->__('required') ?></small>
                        <input type="email" name="login[username]"
                               value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email"
                               title="<?php echo $this->__('Email Address') ?>"
                               placeholder="example@domain.com"
                               required pattern="email"
                               autocomplete="email"/>
                        <span class="form-error"><?php echo $this->__('Please enter your email.') ?></span>
                    </label>
                </div>
                <div class="password-field">
                    <label for="pass"><?php echo $this->__('Password') ?>
                        <small><?php echo $this->__('required') ?></small>
                        <input type="password" name="login[password]"
                               id="pass"
                               title="<?php echo $this->__('Password') ?>"
                               required/>
                        <span class="form-error"><?php echo $this->__('Please enter your password.') ?></span>
                    </label>
                </div>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            </div>
            <div class="buttons-set">
                <a href="<?php echo $this->getForgotPasswordUrl() ?>"
                   class="button hollow"><?php echo $this->__('Forgot Your Password?') ?></a>
                <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send"
                        id="send2">
                    <?php echo $this->__('Login') ?></button>
            </div>
        </div>
        <div class="new-users">
            <div class="content">
                <h2><?php echo $this->__('New Customers') ?></h2>
                <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
            </div>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button float-right"
                        onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';">
                    <?php echo $this->__('Create an Account') ?></button>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout"/>
        <?php endif; ?>
    </form>
</div>
