<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before') ?>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <script type="text/javascript">
        //<![CDATA[
        function captcha() {
            var v = grecaptcha.getResponse();
            if (v.length == 0) {
                document.getElementById('recaptcha_validation').value = "";
                return false;
            }
            if (v.length != 0) {
                document.getElementById('recaptcha_validation').value = "1";
                return true;
            }
        }
        ;
        //]]>
    </script>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" data-abide novalidate
          onsubmit="return jQuery(this) && captcha()">
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>"/>
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>"/>
        <input type="hidden" name="form_key"
               value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
        <div class="personal">
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
            <div class="email-field">
                <label for="email_address"><?php echo $this->__('Email Address') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="email" name="email" id="email_address"
                           value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>"
                           title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>"
                           placeholder="example@domain.com"
                           required pattern="email"
                           autocomplete="email"/>
                    <span class="form-error"><?php echo $this->__('Please enter your email.') ?></span>
                </label>
            </div>
            <?php if ($this->isNewsletterEnabled()): ?>
                <input type="checkbox" name="is_subscribed"
                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign Up for Newsletter')) ?>"
                       value="1"
                       id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>/>
                <label for="is_subscribed"><?php echo $this->__('In den kostenlosen Newsletter eintragen') ?></label>
                <p><strong>Gastrodax-Newsletter:</strong> News, Trends und Angebote per E-Mail inkl. 10 Euro Gutschein
                    <small>(ab 200 Euro Bestellwert)</small>
                    . Die Abmeldung ist jederzeit möglich.
                </p>
            <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>

            <?php if ($this->getShowAddressFields()): ?>
                <input type="hidden" name="create_address" value="1"/>
                <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company"
                                   value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>"
                                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>"
                                   class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>"/>
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?>
                        </label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone"
                                   value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>"
                                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>"
                                   class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"/>
                        </div>
                    </div>
                </li>
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?>
                    </label>
                    <div class="input-box">
                        <input type="text" name="street[]"
                               value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>"
                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>"
                               id="street_1" class="input-text <?php echo $_streetValidationClass ?>"/>
                    </div>
                </li>
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="wide">
                        <div class="input-box">
                            <input type="text" name="street[]"
                                   value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>"
                                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>"
                                   id="street_<?php echo $_i ?>"
                                   class="input-text <?php echo $_streetValidationClass ?>"/>
                        </div>
                    </li>
                <?php endfor; ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city"
                                   value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>"
                                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>"
                                   class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
                                   id="city"/>
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?>
                        </label>
                        <div class="input-box">
                            <select id="region_id" name="region_id"
                                    title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
                                    class="validate-select" style="display:none;">
                                <option
                                        value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                                //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                //]]>
                            </script>
                            <input type="text" id="region" name="region"
                                   value="<?php echo $this->escapeHtml($this->getRegion()) ?>"
                                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>"
                                   class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
                                   style="display:none;"/>
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?>
                        </label>
                        <div class="input-box">
                            <input type="text" name="postcode"
                                   value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>"
                                   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>"
                                   id="zip"
                                   class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>"/>
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
                <input type="hidden" name="default_billing" value="1"/>
                <input type="hidden" name="default_shipping" value="1"/>

            <?php endif; ?>
        </div>
        <div class="login">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <div class="password-field">
                <label for="password"><?php echo $this->__('Password') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="password" name="password" id="password" pattern="password"
                           title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>"
                           required/>
                    <span class="form-error"><?php echo $this->__('Please enter your password.') ?></span>
                    <div id="toolTipPasswordStrength">
                        <div id="toolTipPasswordStrengthWrapper">
                            <div id="passwordStrengthHeadLine"><?php echo $this->__('Passwortstärke: ') ?></div>
                            <div id="passwordStrengthBarContainer">
                                <div id="passwordStrengthBar"></div>
                            </div>
                            <div id="passwordStrengthInfo">
                                <?php echo $this->__('Für ein sicheres Passwort empfehlen wir eine Länge von mindestens 8 Zeichen, der Einsatz von Sonderzeichen, Zahlen und großen sowie kleinen Buchstaben.') ?>
                            </div>
                        </div>
                    </div>
                </label>
            </div>
            <div class="password-confirmation-field">
                <label for="confirmation"><?php echo $this->__('Confirm Password') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="password" name="confirmation" pattern="password"
                           title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm Password')) ?>"
                           id="confirmation"
                           required pattern="alpha_numeric" data-equalto="password"/>
                    <span class="form-error"><?php echo $this->__('Please make sure your passwords match.') ?></span>
                </label>
            </div>
            <script>
                jQuery('#password').focus(function () {
                    jQuery('#toolTipPasswordStrength').css("display", "inline");
                });
                jQuery('#password').blur(function () {
                    jQuery('#toolTipPasswordStrength').css("display", "none");
                });

                var options = {};
                options.ui = {
                    container: "#toolTipPasswordStrength",
                    viewports: {
                        progress: "#passwordStrengthBar",
                        verdict: ".progress-meter-text",
                        errors: "#passwordStrengthHeadLine"
                    },
                    errorMessages: {
                        wordLength: "Ihr Passwort ist zu kurz",
                        wordNotEmail: "Keine Email",
                        wordSimilarToUsername: "Kein Benutzername",
                        wordTwoCharacterClasses: "Keine gleichen Wortgruppen",
                        wordRepetitions: "Zu viele Wiederholungen",
                        wordSequences: "Ihr Passwort enthält Sequenzen"
                    },
                    verdicts: ["zu kurz", "schwach", "gut", "stark", "sehr stark"],
                    showVerdictsInsideProgressBar: true,
                    scores: [16, 26, 38, 45],
                    showErrors: true,
                };
                options.rules = {
                    activated: {
                        wordNotEmail: true,
                        wordLength: true,
                        wordSimilarToUsername: true,
                        wordSequences: true,
                        wordTwoCharacterClasses: true,
                        wordRepetitions: true,
                        wordLowercase: true,
                        wordUppercase: true,
                        wordOneNumber: true,
                        wordThreeNumbers: true,
                        wordOneSpecialChar: true,
                        wordTwoSpecialChar: true,
                        wordUpperLowerCombo: true,
                        wordLetterNumberCombo: true,
                        wordLetterNumberCharCombo: true
                    }
                };
                options.common = {
                    minChar: 8
                };
                jQuery('#password').pwstrength(options);
            </script>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>"
                    class="button float-right"><?php echo $this->__('Submit') ?></button>
            <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                <input name="context" type="hidden" value="checkout"/>
            <?php endif; ?>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
        //]]>
    </script>
</div>
</div>
