<?php
/**
 * @category    Mana
 * @package     ManaPro_FilterAdvanced
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Category layered navigation
 * @author Mana Team
 * Injected instead of standard catalog/layer/view.phtml.
 */
/* @var $this Mage_Core_Block_Template */
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if ($_helpHtml = $this->getFilter()->getFilterOptions()->getHelp()): ?>
|
<div class="m-help">
    <div class="m-text" style="width: <?php echo $this->getFilter()->getFilterOptions()->getHelpWidth() ?>px;">
        <?php echo $_helpHtml ?>
    </div>
    <a href="#" onclick="return false;" class="details m-link">?</a>
</div>
<?php endif; ?>
