<?php $_links = $this->getLinks(); ?>
<?php if (count($_links) > 0): ?>
    <ul class="menu">
        <?php foreach ($_links as $_link): ?>
            <li  <?php if ($_link->getUrl() == '/checkout/cart'): ?>class="shopping-cart"<?php endif; ?>>
                <a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getBeforeText() ?>
                    <?php if ($_link->getUrl() == '/checkout/cart'): ?>
                        <?php $_cartQty = Mage::getSingleton('checkout/cart')->getItemsCount(); ?>
                        <span class="cart-qty<?php if ($_cartQty >= 10): ?>-10<?php endif; ?>">
                                <?php echo $_cartQty; ?>
                            </span>
                    <?php endif; ?>
                    <span class="title"><?php echo $_link->getTitle() ?></span>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>