<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
 * @package Auto Add Promo Items
 */
?>
<?php
/** @var Amasty_Promo_Block_Items $this */
$products = $this->getItems();
$mode = $this->getModeName();
?>

<?php echo $this->getPopupHeader() ?>
<?php echo $this->getOptionsJs() ?>
<?php echo $this->getCalendarJs() ?>
<ul id="ampromo-items" class="gift-grid">
    <?php foreach ($products as $product): ?>
        <?php echo $this->renderItem($product) ?>
    <?php endforeach ?>
</ul>