<div class="page-title">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<script type="text/javascript">
    //<![CDATA[
    function captcha() {
        var v = grecaptcha.getResponse();
        if (v.length == 0) {
            document.getElementById('recaptcha_validation').value = "";
            return false;
        }
        if (v.length != 0) {
            document.getElementById('recaptcha_validation').value = "1";
            return true;
        }
    }
    ;
    //]]>
</script>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" data-abide
      novalidate
      onsubmit="return jQuery(this) && captcha()">
    <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
    <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
    <div class="email-field">
        <label for="email_address"><?php echo $this->__('Email Address') ?>
            <small><?php echo $this->__('required') ?></small>
            <input type="email" name="email" id="email_address"
                   value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>"
                   placeholder="example@domain.com"
                   required/>
        </label>
        <small class="form-error"><?php echo $this->__('Please enter your email.') ?></small>
    </div>
    <?php echo $this->getChildHtml('form.additional.info'); ?>
    <div class="button-group">
        <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"
           class="button hollow"><?php echo $this->__('Back to Login') ?></a>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>"
                class="button"><?php echo $this->__('Submit') ?></button>
    </div>
</form>