<div class="account-login">
    <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.login.extra') ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" data-abide novalidate>
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="registered-users">
            <div class="content">
                <h2><?php echo $this->__('Registered Customers') ?></h2>
                <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                <div class="email-field">
                    <label for="email">
                        <?php echo $this->__('Email Address') ?>
                        <small><?php echo $this->__('required') ?></small>
                        <input type="text"
                               name="login[username]"
                               value="<?php echo $this->escapeHtml($this->getUsername()) ?>"
                               id="email"
                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>"
                               placeholder="example@domain.com"
                               required pattern="email"
                               autocomplete="email" />
                        <span class="form-error"><?php echo $this->__('Please enter your email.') ?></span>
                    </label>
                </div>
                <div class="password-field">
                    <label for="pass">
                        <?php echo $this->__('Password') ?>
                        <small><?php echo $this->__('required') ?></small>
                        <input type="password"
                               name="login[password]"
                               id="pass"
                               title="<?php echo Mage::helper('core')->quoteEscape($this->__('Password')) ?>"
                               required />
                        <span class="form-error"><?php echo $this->__('Please enter your password.') ?></span>
                    </label>
                </div>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </div>
            <div class="buttons-set">
                <a href="<?php echo $this->getForgotPasswordUrl() ?>"
                   class="button hollow"><?php echo $this->__('Forgot Your Password?') ?></a>
                <button type="submit" class="button"
                        title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>" name="send"
                        id="send2"><?php echo $this->__('Login') ?></button>
            </div>
        </div>
        <div class="new-users">
            <h2><?php echo $this->__('New Customers') ?></h2>
            <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
            <div class="buttons-set">
                <button type="button"
                        title="<?php echo Mage::helper('core')->quoteEscape($this->__('Create an Account')) ?>"
                        class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';">
                    <span><span><?php echo $this->__('Create an Account') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>
