<div class="page-title">
    <h1><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate" data-abide novalidate>
    <div class="password-field">
        <label for="password"><?php echo $this->__('New Password'); ?>
            <small><?php echo $this->__('required') ?></small>
            <input type="password" name="password" id="password" required/>
            <small class="form-error"><?php echo $this->__('Please enter your password.') ?></small>
            <div id="toolTipPasswordStrength">
                <div id="toolTipPasswordStrengthWrapper">
                    <div id="passwordStrengthHeadLine"><?php echo $this->__('Passwortstärke: ') ?></div>
                    <div id="passwordStrengthBarContainer">
                        <div id="passwordStrengthBar"></div>
                    </div>
                    <div id="passwordStrengthInfo">
                        <?php echo $this->__('Für ein sicheres Passwort empfehlen wir eine Länge von mindestens 8 Zeichen, der Einsatz von Sonderzeichen, Zahlen und großen sowie kleinen Buchstaben.') ?>
                    </div>
                </div>
            </div>
        </label>
    </div>
    <div class="password-confirmation-field">
        <label for="confirmation"><?php echo $this->__('Confirm New Password'); ?>
            <small><?php echo $this->__('required') ?></small>
            <input type="password" name="confirmation" id="confirmation" required data-equalto="password"/>
            <small class="form-error"><?php echo $this->__('Please make sure your passwords match.') ?></small>
        </label>
    </div>
    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>"
            class="button float-right"><?php echo $this->__('Reset a Password'); ?></button>
</form>
