<div class="page-title">
    <h1><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate" data-abide novalidate>
    <div class="password-field">
        <label for="password"><?php echo $this->__('New Password'); ?>
            <small><?php echo $this->__('required') ?></small>
            <input type="password" name="password" id="password" required/>
            <small class="form-error"><?php echo $this->__('Please enter your password.') ?></small>
            <div id="toolTipPasswordStrength">
                <div id="toolTipPasswordStrengthWrapper">
                    <div id="passwordStrengthHeadLine"><?php echo $this->__('Passwortstärke: ') ?></div>
                    <div id="passwordStrengthBarContainer">
                        <div id="passwordStrengthBar"></div>
                    </div>
                    <div id="passwordStrengthInfo">
                        <?php echo $this->__('Für ein sicheres Passwort empfehlen wir eine Länge von mindestens 8 Zeichen, der Einsatz von Sonderzeichen, Zahlen und großen sowie kleinen Buchstaben.') ?>
                    </div>
                </div>
            </div>
        </label>
    </div>
    <div class="password-confirmation-field">
        <label for="confirmation"><?php echo $this->__('Confirm New Password'); ?>
            <small><?php echo $this->__('required') ?></small>
            <input type="password" name="confirmation" id="confirmation" required data-equalto="password"/>
            <small class="form-error"><?php echo $this->__('Please make sure your passwords match.') ?></small>
        </label>
    </div>
    <script>
        jQuery('#password').focus(function () {
            jQuery('#toolTipPasswordStrength').css("display", "inline");
        });
        jQuery('#password').blur(function () {
            jQuery('#toolTipPasswordStrength').css("display", "none");
        });

        var options = {};
        options.ui = {
            container: "#toolTipPasswordStrength",
            viewports: {
                progress: "#passwordStrengthBar",
                verdict: ".progress-meter-text",
                errors: "#passwordStrengthHeadLine"
            },
            errorMessages: {
                wordLength: "Ihr Passwort ist zu kurz",
                wordNotEmail: "Keine Email",
                wordSimilarToUsername: "Kein Benutzername",
                wordTwoCharacterClasses: "Keine gleichen Wortgruppen",
                wordRepetitions: "Zu viele Wiederholungen",
                wordSequences: "Ihr Passwort enthält Sequenzen"
            },
            verdicts: ["zu kurz", "schwach", "gut", "stark", "sehr stark"],
            showVerdictsInsideProgressBar: true,
            scores: [16, 26, 38, 45],
            showErrors: true,
        };
        options.rules = {
            activated: {
                wordNotEmail: true,
                wordLength: true,
                wordSimilarToUsername: true,
                wordSequences: true,
                wordTwoCharacterClasses: true,
                wordRepetitions: true,
                wordLowercase: true,
                wordUppercase: true,
                wordOneNumber: true,
                wordThreeNumbers: true,
                wordOneSpecialChar: true,
                wordTwoSpecialChar: true,
                wordUpperLowerCombo: true,
                wordLetterNumberCombo: true,
                wordLetterNumberCharCombo: true
            }
        };
        options.common = {
            minChar: 8
        };
        jQuery('#password').pwstrength(options);
    </script>
    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>"
            class="button"><?php echo $this->__('Reset a Password'); ?></button>
</form>
