<?php echo $this->getChildHtml('checkout.onepage.login.extra') ?>
<div class="col2-set">
    <?php echo $this->getChildHtml('login_before') ?>
    <div class="col-1">
        <p class="h2"><?php echo $this->__('weitere Zahlungsarten') ?></p>
        <h3><?php if ($this->getQuote()->isAllowedGuestCheckout()): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
        <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
        <?php else: ?>
            <p><strong><?php echo $this->__('Register and save time!') ?></strong><br/>
                <?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php endif; ?>
        <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
            <ul class="form-list">
                <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:guest"
                               value="guest"<?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?>
                               class="radio"/><label
                                for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                    </li>
                <?php endif; ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:register"
                           value="register"<?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?>
                           class="radio"/><label for="login:register"><?php echo $this->__('Register') ?></label>
                </li>
            </ul>
            <h4><?php echo $this->__('Register and save time!') ?></h4>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked"/>
        <?php endif; ?>
        <div class="buttons-set">
            <button type="button" class="button" onclick="checkout.setMethod();">
                <?php echo($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?>
            </button>
        </div>
    </div>
    <div class="col-2">
        <h3><?php echo $this->__('Login') ?></h3>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post" data-abide novalidate>
            <?php echo $this->getBlockHtml('formkey'); ?>
            <h4><?php echo $this->__('Already registered?') ?></h4>
            <p><?php echo $this->__('Please log in below:') ?></p>
            <div class="field">
                <label for="login-email"><?php echo $this->__('Email Address') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false"
                           id="login-email"
                           name="login[username]"
                           value="<?php echo $this->escapeHtml($this->getUsername()) ?>"
                           placeholder="example@domain.com"
                           required/>
                </label>
            </div>
            <div class="field">
                <label for="login-password"><?php echo $this->__('Password') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="password" id="login-password" name="login[password]" required/>
                </label>
            </div>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <div class="buttons-set">
                <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"
                   class="button hollow"><?php echo $this->__('Forgot your password?') ?></a>
                <button type="submit" class="button" onclick="onepageLogin(this)">
                    <?php echo $this->__('Login') ?></button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt) {
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button) {
        if (loginForm.validator && loginForm.validator.validate()) {
            button.disabled = true;
            loginForm.submit();
        }
    }
    //]]>
</script>
