<?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
    <div id="billing-progress-opcheckout">
        <?php echo $this->getChildHtml('billing.progress') ?>
        <hr>
    </div>
<?php endif; ?>

<?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
    <div id="shipping-progress-opcheckout">
        <?php echo $this->getChildHtml('shipping.progress') ?>
        <hr>
    </div>
<?php endif; ?>

<?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
    <div id="shipping_method-progress-opcheckout">
        <?php echo $this->getChildHtml('shippingmethod.progress') ?>
        <hr>
    </div>
<?php endif; ?>

    <div id="comment-progress-opcheckout">
        <?php echo $this->getChildHtml('comment.progress') ?>
        <hr>
    </div>

<?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
    <div id="payment-progress-opcheckout">
        <?php echo $this->getChildHtml('payment.progress') ?>
    </div>
<?php endif; ?>
<hr>
