<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
       <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
    //]]>
    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <div class="buttons-set" id="shipping-method-buttons-container">
        <button type="button" class="button" onclick="shippingMethod.save()"><?php echo $this->__('Continue') ?></button>
    </div>
    <?php echo $this->getBlockHtml('formkey') ?>
</form>
<div id="shipping-method-please-wait" class="please-wait" style="display:none;">
    <div class="centered">
        <i class="fas fa-circle-notch fa-spin fa-3x fa-fw margin-bottom"></i>
    </div>
</div>
