<div id="remember-me" class="reveal" data-reveal>
    <h2 id="reveal-modal-title"><?php echo $this->__('What\'s this?') ?></h2>
    <p><?php echo $this->__('Checking &quot;Remember Me&quot; will let you access your shopping cart on this computer when you are logged out') ?></p>
    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>