<?php
/**
  * Loewenstark_Newsletter
  *
  * @category  Loewenstark
  * @package   Loewenstark_Newsletter
  * @author    Mathis Klooss <m.klooss@loewenstark.de>
  * @copyright 2013 Loewenstark Web-Solution GmbH (http://www.loewenstark.de). All rights served.
  * @license     https://github.com/mklooss/Loewenstark_Newsletter/blob/master/README.md
  */
?>
<?php if ($this->isEnabled() && $this->getStatus() == $this->getStatusByName("STATUS_UNCONFIRMED")): ?>
    <a class="button" href="<?php echo $this->getResendUrl(); ?>" title="<?php echo $this->__("resend subscription request"); ?>"><?php echo $this->__("resend subscription request"); ?></a>
<?php endif; ?>
