<div class="col2-set<?php if (!$this->helper('customer')->isRegistrationAllowed() && !$this->getQuote()->isAllowedGuestCheckout()) echo ' login-only' ?>">
    <div class="col-1">
        <?php echo $this->getChildHtml('login_before') ?>
        <h3>
            <?php if ($this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed()): ?>
                <?php echo $this->__('Checkout as a Guest or Register') ?>
            <?php elseif ($this->getQuote()->isAllowedGuestCheckout() && !$this->helper('customer')->isRegistrationAllowed()): ?>
                <?php echo $this->__('Checkout as a Guest') ?>
            <?php else: ?>
                <?php echo $this->__('Register to Create an Account') ?>
            <?php endif; ?>
        </h3>
        <?php if (!$this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed()): ?>
            <p class="description"><?php echo $this->__('Register and save time!') ?><br/>
                <?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php elseif ($this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed()): ?>
            <p class="description"><?php echo $this->__('Register with us for future convenience:') ?></p>
        <?php endif ?>
        <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
            <ul class="form-list">
                <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:guest"
                               value="guest"<?php if ($this->getQuote()->getCheckoutMethod() != Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER): ?> checked="checked"<?php endif; ?>
                               class="radio"/><label
                                for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                    </li>
                <?php endif; ?>
                <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:register"
                               value="register"<?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?>
                               class="radio"/><label
                                for="login:register"><?php echo $this->__('Register and Checkout') ?></label>
                    </li>
                <?php endif; ?>
            </ul>
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked"/>
        <?php endif; ?>
        <div class="buttons-set">
            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();">
                    <?php echo $this->__('Continue') ?></button>
            <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
                <button id="onepage-guest-register-button" type="button" class="button"
                        onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl(); ?>'">
                    <?php echo $this->__('Register') ?></button>
            <?php else: ?>
                <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                    <button id="onepage-guest-register-button" type="submit" class="button">
                        <?php echo $this->__('Register') ?></button>
                </form>
            <?php endif; ?>
        </div>
    </div>
    <div class="col-2">
        <h3><?php echo $this->__('Returning Customers') ?></h3>
        <?php echo $this->getMessagesBlock()->toHtml() ?>

        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post" data-abide novalidate>
            <?php echo $this->getBlockHtml('formkey'); ?>
            <p class="description"><?php echo $this->__('Sign in to speed up your checkout process') ?></p>
            <div class="field">
                <label for="login-email"><?php echo $this->__('Email Address') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false"
                           id="login-email"
                           name="login[username]"
                           value="<?php echo $this->escapeHtml($this->getUsername()) ?>"
                           placeholder="example@domain.com"
                           required/>
                </label>
            </div>
            <div class="field">
                <label for="login-password"><?php echo $this->__('Password') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="password" id="login-password" name="login[password]" required/>
                </label>
            </div>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            <input name="context" type="hidden" value="checkout"/>
            <div class="buttons-set">
                <a class="button hollow"
                   href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo $this->__('Forgot your password?') ?></a>
                <button type="submit" class="button"
                        onclick="onepageLogin(this)"><?php echo $this->__('Login') ?></button>
            </div>
        </form>
    </div>
</div>
    <script type="text/javascript">
        //<![CDATA[
        var loginForm = new VarienForm('login-form', true);
        $('login-email').observe('keypress', bindLoginPost);
        $('login-password').observe('keypress', bindLoginPost);
        function bindLoginPost(evt){
            if (evt.keyCode == Event.KEY_RETURN) {
                loginForm.submit();
            }
        }
        function onepageLogin(button)
        {
            if(loginForm.validator && loginForm.validator.validate()){
                button.disabled = true;
                loginForm.submit();
            }
        }
        //]]>
    </script>
<?php
$registerParam = $this->getRequest()->getParam('register');
if ($registerParam || $registerParam === ''):
    ?>
    <script type="text/javascript">
        //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
        //]]>
    </script>
<?php endif; ?>