<?php
/**
 * @category    Mana
 * @package     ManaPro_FilterClear
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Category layered navigation
 * @author Mana Team
 * Injected instead of standard catalog/layer/view.phtml.
 */
/* @var $this Mage_Core_Block_Template */
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if ($_clearUrl = Mage::helper('manapro_filterclear')->getClearUrl($this->getFilter())) : ?>
    <div class="m-filterclear">
        <a href="<?php echo $_clearUrl ?>" title="<?php echo $this->__('Clear') ?>" class="btn-remove"><?php echo $this->__('Clear') ?></a>
    </div>
<?php endif; ?>
