<?php
/**
 * @project gastrodax
 *
 * @author pbreitsprecher
 * @copyright 2016
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 *
 * @last_modified 11.11.15 03:10
 * @file items.phtml
 *
 */
/**
 * Template for showing options for filter as a list of checkboxes
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute init() method.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'before_items', array('block' => $this)) ?>
<ol class="m-filter-checkboxes <?php echo $this->getFilterOptions()->getIsReverse() ? 'm-reverse' : '' ?>">
    <?php foreach ($this->getItems() as $_item): ?>
        <li <?php echo $this->getListItemClass($_item) ?> >
            <?php // MANA BEGIN ?>
            <?php if (!$this->getFilterOptions()->getDisableNoResultOptions() || $_item->getCount() || $_item->getMSelected()): ?>
            <div class="switch-toggle-wrapper">
                <div class="switch tiny">
                    <input class="switch-input" type="checkbox" id="<?php echo $_item->getUniqueId($this) ?>"
                           value="<?php echo $_item->getValue() ?>"
                           <?php if ($_item->getMShowSelected()): ?>checked="checked"<?php endif; ?>
                           onClick="setLocation('<?php echo rawurldecode($this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl())) ?>');"/>
                    <label class="switch-paddle" for="<?php echo $_item->getUniqueId($this) ?>">
                        <span class="show-for-sr<?php if ($_item->getMShowSelected()): ?> m-selected-checkbox-item<?php endif; ?>"
                            title="<?php echo $this->escapeHtml($_item->getLabel()) ?>"><?php echo $this->escapeHtml($_item->getLabel()) ?></span><?php if (Mage::getStoreConfigFlag('mana_filters/display/count')) : ?>
                            (<?php echo $_item->getCount() ?>)
                        <?php endif; ?></label>
                </div>
                <span><?php echo $this->escapeHtml($_item->getLabel()) ?></span>
            </div>
            <?php else: ?>
            <div class="switch-toggle-wrapper">
                <div class="switch tiny">
                    <input class="switch-input" type="checkbox" id="<?php echo $_item->getUniqueId($this) ?>"
                           value="<?php echo $_item->getValue() ?>"
                           <?php if ($_item->getMShowSelected()): ?>checked="checked"<?php endif; ?>
                           disabled="disabled"/>
                    <label class="switch-paddle" for="<?php echo $_item->getUniqueId($this) ?>">
                        <span class="show-for-sr<?php if ($_item->getMShowSelected()): ?> m-selected-checkbox-item<?php endif; ?>"
                                title="<?php echo $this->escapeHtml($_item->getLabel()) ?>"><?php echo $this->escapeHtml($_item->getLabel()) ?></span><?php if (Mage::getStoreConfigFlag('mana_filters/display/count')) : ?>
                            (<?php echo $_item->getCount() ?>)
                        <?php endif; ?></label>
                </div>
                <span><?php echo $this->escapeHtml($_item->getLabel()) ?></span>
            </div>
            <?php endif; ?>
            <?php // MANA END ?>
        </li>
    <?php endforeach ?>
</ol>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'after_items', array('block' => $this)) ?>
