<?php
$_configHelper = Mage::helper('searchautocomplete/config');
$_product = $this->getItem();
?>
<li data-url="<?php echo $_product->getProductUrl() ?>">
    <?php if ($_configHelper->isShowImage()): ?>

            <img src="<?php echo $this->helper('mstcore/image')->init($_product, 'thumbnail', 'catalog/product')->resize($_configHelper->getImageWidth(), $_configHelper->getImageHeight()) ?>"
                 width="<?php echo $_configHelper->getImageWidth() ?>px"
                 height="<?php echo $_configHelper->getImageHeight() ?>px"/>
    <?php endif ?>
    <a class="name highlight"
       href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>

    <?php if ($_configHelper->isShowShortDescription()): ?>
        <div class="highlight">
            <?php echo Mage::helper('core/string')->truncate(strip_tags($this->getProductShortDescription($_product)), $_configHelper->getShortDescriptionLen()) ?>
        </div>
    <?php endif ?>

    <?php if ($_configHelper->isShowPrice()): ?>
        <?php echo $this->getPriceHtml($_product, false) ?>
    <?php endif ?>
</li>